worker:
  sandbox:
    runner-type: linux-amd64-dotnet-7
    container-operations-timeout-ms: 60000 # 1 min
    job-timeout-ms: 120000 # 2 min
    job-files-host-dir: ${WORKER_JOB_FILES_HOST_DIT:/tmp/scripts}
    job-files-container-dir: /tmp/script
    job-script-file-name: main.csx
    max-containers: 2
    container:
      image-name: semyonnaumov/sandbox
      image-tag: ${worker.sandbox.runner-type}
      image: ${worker.sandbox.container.image-name}:${worker.sandbox.runner-type}
      name-prefix: sandbox-job-
      enable-resource-limits: ${WORKER_ENABLE_RESOURCE_LIMITS:true}
      memory-mb: 1024
      memory-reservation-mb: 256
      cpu-period-micros: 200000
      cpu-quota-micros: 100000
      cpu-shares: 512
      pids-limit: 100
      blkio-weight: 400
      storage-size: 5G # currently not supported
  docker-client:
    docker-host: unix:/var/run/docker.sock
    docker-tls-verify: false
    docker-cert-path: ${WORKER_DOCKER_CERT_PATH}
    registry-url: docker.io
    registry-user: ${WORKER_REGISTRY_USER:comnaumovdotnetscripts}
    registry-password: ${WORKER_REGISTRY_PASSWORD:1234567890}
    registry-email: ${WORKER_REGISTRY_EMAIL:user@mail.com}
    max-connections: 100
    connection-timeout-sec: 30
    response-timeout-sec: 45
  kafka:
    broker-url: ${WORKER_KAFKA_BROKER_URL:localhost:8097}
    reconnect-backoff-ms: 100
    reconnect-backoff-max-ms: 10000
    jobs-topic-name: pending-${worker.sandbox.runner-type}
    running-topic-name: running
    finished-topic-name: finished
    producer-acks: 1
    consumer-concurrency: ${worker.sandbox.max-containers}
    consumer-group: workers.${worker.sandbox.runner-type}
  kafka-admin:
    broker-url: ${worker.kafka.broker-url}
    reconnect-backoff-ms: ${worker.kafka.reconnect-backoff-ms}
    reconnect-backoff-max-ms: ${worker.kafka.reconnect-backoff-max-ms}
    replication-factor: 2
    jobs-topic-name: ${worker.kafka.jobs-topic-name}
    jobs-topic-partitions: 2
    running-topic-name: ${worker.kafka.running-topic-name}
    running-topic-partitions: 2
    finished-topic-name: ${worker.kafka.finished-topic-name}
    finished-topic-partitions: 2
