worker:
  sandbox:
    worker-type: linux-amd64-dotnet-7
    max-concurrent-sandboxes: 8
    container-operations-timeout-ms: 60000 # 1 min
    job-timeout-ms: 120000 # 2 min
    sandbox-image: sandbox:${worker.sandbox.worker-type}
    sandbox-container-prefix: job-
    script-file-name: main.csx # todo add env to dockerfile?
#    script-files-on-host-dir: /tmp/scripts # Application folder to write script files to
    script-files-on-host-dir: /Users/snaumov/Desktop/scripts # Application folder to write script files to
    script-file-in-container-dir: /tmp/script # DinD container script file location
  docker-client:
    docker-host: unix:/var/run/docker.sock # or tcp://localhost:2376
    docker-tls-verify: false
    docker-cert-path: /Users/snaumov/.docker
    registry-user: registryUser
    registry-password: registryPass
    registry-email: registryMail
    registry-url: registryUrl
  kafka:
    broker-url: localhost:9092
    jobs-topic-name: pending-${worker.sandbox.worker-type}
    running-topic-name: running
    finished-topic-name: finished
    producer-acks: 1
    consumer-concurrency: ${worker.sandbox.max-concurrent-sandboxes}
    consumer-group: workers.${worker.sandbox.worker-type}

logging:
  level:
    com.naumov.dotnetscriptsworker: debug
